### PR TITLE
Multirobot functionality

### PR DESCRIPTION
**Pull request by heuristicus**
- Many required changes to allow multiple robots to be represented in director, the robot's name (as defined in configuration) is used in many places to allow components associated with different robots to be distinguished
- Configuration file reading changes. Files are per-robot and each robot has a configuration loaded by drcargs, which is separate for each robot
- Initialisation of perception sources now based on configuration file rather than being hardcoded
- Startup changes to allow multiple robots to be initialised

This PR also depends on these pull requests (Note: I have closed all PRs other than this one to reduce commit message spam):

- https://github.com/ori-drs/director_drs/pull/127
- https://github.com/ori-drs/director_ros/pull/3
- https://github.com/ori-drs/vtk_ros/pull/16
- https://github.com/ori-drs/navigation_drs/pull/48
- https://github.com/ori-drs/drs_base/pull/224
- https://github.com/ori-drs/multi_gait_scheduler/pull/36

And the master branch at https://github.com/ori-drs/multirobot_drs for configuration of nimbro communication

These are the branches used:

- https://github.com/ori-drs/director/tree/multimaster
- https://github.com/ori-drs/director_drs/tree/multimaster
- https://github.com/ori-drs/director_ros/tree/multimaster
- https://github.com/ori-drs/vtk_ros/tree/multimaster
- https://github.com/ori-drs/navigation_drs/tree/multimaster
- https://github.com/ori-drs/drs_base/tree/multimaster
- https://github.com/ori-drs/multirobot_drs
- https://github.com/ori-drs/multi_gait_scheduler/tree/multimaster

## Testing procedure

This script can be used as a shortcut to checkout the relevant branches in all related repositories. It must be run in `catkin_ws/src` to work.

```bash
#!/bin/bash

if [ $# -ge 1 ]; then
    branch="master"
else
    branch="multimaster"
fi

repos="director director_drs director_ros vtk_ros navigation_drs drs_base multi_gait_scheduler"

for repo in $repos; do
    echo "checking out $branch in $repo"
    cd $repo
    git checkout $branch
    cd ..
done
```

### Single robot

No special setup is required if using a single robot. Using the standard launch files as normal should produce the same functionality as before.

#### Single robot with udp

This is also possible, using `rosrun multirobot_drs bringup_anymal_single.sh`. See the multiple robots instructions for additional information about setup.

### Multiple robots

With multiple robots, the testing is more complicated. It necessary to use https://github.com/ori-drs/docker_drs as multirobot_drs makes use of docker to isolate the robots. This is necessitated by gazebo not functioning correctly with multiple instances of it running at the same time - the tf publishers created by gazebo publish to the same place and thus cause the anymal to consistently fall over due to interfering signals.

To build the required docker containers it should be sufficient to run the `build_all.sh` script in `docker_drs`. Note that the build uses a lot of cpu. If this build doesn't work (It hasn't worked for me while using the vpn), download the image from the ori repositories with

```
docker pull ori-ci-gateway.robots.ox.ac.uk:12002/drs/base-multirobot-18.04:latest
```

For scripts to function correctly, we need to tag the image:

```
docker tag ori-ci-gateway.robots.ox.ac.uk:12002/drs/base-multirobot-18.04:latest drs:base
```

This image is not fully up to date because of aforementioned vpn issues but will still function. In order to build the rest of the required images, layering on top of the base image to provide GUI and multirobot components, run `build_all.sh nobase`.

`tmux` and `tmuxinator` are used to simplify running all the required files. They can be installed with

```
sudo apt install tmux tmuxinator
```

You can find information about tmux keybindings at https://tmuxcheatsheet.com/

To start everything, use `rosrun multirobot_drs bringup_anymal_multi.sh`. This will start 3 tmux sessions, one for the operator, and one for each anymal.

To attach to the tmux session, use `tmux a -t [session]`. You can see the name of tmux sessions using `tmux ls`. With the anymal bringup, there will be three sessions which can be attached to using

```
tmux a -t operator
tmux a -t first
tmux a -t second
```

First and second are the names of the robots (as specified in the bringup script).

The operator tmux has three panes - top left is roscore, top right is director, and bottom are the nimbro communications nodes.

The first tab in each robot tmux is the same configuration as the one for the operator. The anymal has an additional tab for robot motion where the position controller and multi gait nodes are run.

To create a terminal on one of the robots in docker, use `docker exec -it containername bash`. You can check the names of the currently running containers with `docker container list`. The names of the containers correspond to the names of the robots.

Note that there are still some issues with tf broadcasting. Some of these can be fixed by restarting the nimbro nodes on the robot side. Sometimes doing it only once doesn't fix the issue. Once you stop seeing `velodyne` error messages in the director pane, things should be mostly ok. The velodyne clouds should be visible. In the multirobot case the elevation map is still not available. This may be due to my machine not having enough processing power (with only 1 anymal in docker I get 0.3hz on elevation map topic).

### CODE REVIEW

**Comment by benoit-robotics** [comment]
It seems that  the tests of director are failing

**Comment by heuristicus** [comment]
Tests should be functioning correctly now, need to pull drs_base and director.

**Comment by benoit-robotics** [comment]
close but no bananas

**Comment by heuristicus** [comment]
What's failing?

**Comment by heuristicus** [comment]
That won't work because it's not using the multimaster branch of drs_base. Only local testing functions since you can check out all the branches you need.

**Comment by benoit-robotics** [comment]
It's using the multimaster branch of drs_base : http://ori-ci-gateway.robots.ox.ac.uk:10301/job/drs_pr_ori_drs_director/77/consoleFull , you can see that nimbro_network is cloned. On the build server all the branches named "multimaster" are checked out on all the repositories ( if this branch exists of course )

**Comment by benoit-robotics** [comment]
I am getting this error in single robot mode when launching director with "roslaunch director_drs anymal_sim.launch"
> Traceback (most recent call last):
>   File "<string>", line 7, in <module>
>   File "/home/benoit/catkin_ws/devel/.private/director/lib/python2.7/site-packages/director/startup.py", line 348, in <module>
>     for _, robotConfig in drcargs.DirectorConfig.getDefaultInstance().robotConfigs.iteritems():
>   File "/home/benoit/catkin_ws/devel/.private/director/lib/python2.7/site-packages/director/drcargs.py", line 228, in getDefaultInstance
>     raise Exception('Robot config files not defined. You must pass at least one. '
> Exception: Robot config files not defined. You must pass at least one. Use --robot-config <filename> on the command line.

**Comment by heuristicus** [comment]
Should work now with update to director_drs.

**Comment by benoit-robotics** [comment]
Did you test the new_lab mission ? It doesn't work for me

**Comment by heuristicus** [comment]
I just tried it on master and it doesn't work there either. Gets stuck at dynamic trot to goal in front of the stairs.

**Comment by benoit-robotics** [comment]
Did you try with your branches as well ? I think that it wasn't working before that

**Comment by benoit-robotics** [comment]
It works for me on master ( I didn't execute the whole mission, but it can climb the stairs ). Are you sure that you clicked on "approve continue" or "approve pose" ? Maybe it's waiting for an approval

**Comment by heuristicus** [comment]
For me there are some issues with the position controller and free gait actions not working. Seems as though it hangs waiting for the action server. This is on master on all branches and I made sure to recompile everything.

**Comment by heuristicus** [comment]
Tested the new_lab mission on multimaster branches with the fix to position_controller and it works on a single anymal both with and without using docker+nimbro.

I also tried running two docker instances at once, and while the mission executes correctly the robots fall over when using dynamic trot, I think because my processor/network is overloaded and so the message rate isn't high enough for the controller.

**Comment by benoit-robotics** [comment]
When you set a walking goal in director, this error appears : 

> ERROR: In /build/vtk6-VHOYAG/vtk6-6.3.0+dfsg1/Interaction/Widgets/vtkAbstractWidget.cxx, line 118
> vtkFrameWidget (0x55ecba7cee50): The interactor must be set prior to enabling the widget

but it works though

**Comment by benoit-robotics** [comment]
Also I don't see the head camera cloud and the ground camera cloud. When using roslaunch anymal_boxy_sim sim_new_lab.launch.

**Comment by benoit-robotics** [comment]
And the toggle image view is broken ( lens icon on the top, it should display the images coming from the two front cameras ).

> Traceback (most recent call last):
>   File "/home/benoit/catkin_ws/devel/.private/director/lib/python2.7/site-packages/director/startup.py", line 151, in toggle
>     self.manager.show()
>   File "/home/benoit/catkin_ws/devel/.private/director/lib/python2.7/site-packages/director/cameraview.py", line 439, in show
>     if self.haveImage():
>   File "/home/benoit/catkin_ws/devel/.private/director/lib/python2.7/site-packages/director/cameraview.py", line 447, in haveImage
>     image = self.imageManager.getImage(imageName)
> TypeError: getImage() takes exactly 3 arguments (2 given)
> Traceback (most recent call last):
>   File "/home/benoit/catkin_ws/devel/.private/director/lib/python2.7/site-packages/director/timercallback.py", line 92, in _timerEvent
>     result = self.tick()
>   File "/home/benoit/catkin_ws/devel/.private/director/lib/python2.7/site-packages/director/timercallback.py", line 49, in tick
>     return self.callback()
>   File "/home/benoit/catkin_ws/devel/.private/director/lib/python2.7/site-packages/director/cameraview.py", line 459, in updateView
>     currentUtime = max(self.imageManager.updateImage(imageName), currentUtime)
> TypeError: updateImage() takes exactly 3 arguments (2 given)

**Comment by benoit-robotics** [comment]
The tab "Camera view" doesn't work either

**Comment by benoit-robotics** [comment]
I played back anymal_2020-02-18-14-39-02.bag . I got 
> Traceback (most recent call last):
>   File "/home/benoit/catkin_ws/src/director_ros/src/director_ros/dd_ros_subscriber.py", line 26, in handle_message
>     self.callback(msg)
>   File "/home/benoit/catkin_ws/src/director_drs/src/director_drs/autonomytaskpanel.py", line 600, in missionStatusCallback
>     self.drawMission()
>   File "/home/benoit/catkin_ws/src/director_drs/src/director_drs/autonomytaskpanel.py", line 544, in drawMission
>     self.tfDrawer.drawFrame(thisTask.pose, name, timestamp=None, frame=None, color=color, parent=obj)
>   File "/home/benoit/catkin_ws/src/director_ros/src/director_ros/tfdrawer.py", line 104, in drawFrame
>     obj = tf_vis.updateFrame(name, transform, frame, **kwargs)
>   File "/home/benoit/catkin_ws/src/director_ros/src/director_ros/tfvisualization.py", line 549, in updateFrame
>     obj = showFrame(name, transform, frame, **kwargs)
>   File "/home/benoit/catkin_ws/src/director_ros/src/director_ros/tfvisualization.py", line 530, in showFrame
>     assert view
> AssertionError

Please check before that it works on master branch

**Pull request merged**
