### PR TITLE
removes lot and lots of unused DRC-era code

### PR DESCRIPTION
**Pull request by mauricefallon**
@heuristicus  and @benoit-robotics  : this removes thousands of unused 'demo' code for Atlas

### CODE REVIEW

**Comment by mauricefallon** [comment]
@heuristicus  could you do a little testing to make sure nothing complains when running in simulation?

**Comment by heuristicus** [comment]
If we are going to move files around we should use the opportunity provided by losing the history of the file to run pep8 over everything to have it to a standard, and also remove all unused imports since there are many files with a large number of those.

**Comment by benoit-robotics** [comment]
I would also be good to use a standard code style for our c++ code

**Comment by heuristicus** [comment]
For C++ there is a ROS standard if we want to use that https://wiki.ros.org/CppStyleGuide. [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) provides a way of applying styles to code, and there is a style for the ROS standard available. But since director isn't ROS, we might prefer to use Google or LLVM styles, or use those as a basis for creating our own desired style.

**Comment by benoit-robotics** [comment]
Can we merge this ?

**Comment by heuristicus** [comment]
No, there is going to be more work on this.

**Comment by mauricefallon** [comment]
I'm going to close this PR until you are done

**Comment by heuristicus** [comment]
@mauricefallon I've finished going through the spreadsheet and all non-core files which you pointed to for removal have been removed if possible. There aren't any major structural changes. The most significant change is to roboturdf which now has code from packagepath and footstepsdriverpanel. That code was used to read package paths for urdf data from `ROS_PACKAGE_PATH`, and computing the feet midpoint which is used in a few places. Code used when adding walking goals moved from the footstepsdriverpanel into robotviewbehaviours.

**Comment by heuristicus** [comment]
Related issue: https://github.com/ori-drs/drs_base/issues/183

**Comment by mauricefallon** [comment]
I was aware of this code for getting the feet midpoint. As long as its moved somewhere reasonable we can reposition it if needed.

Footstepsdriverpanel is all depreciated code (for planning footsteps with Atlas)

Would you like me to test this PR a bit?

.... Great job by the way. 35,000 lines of code removed - Yikes!

**Comment by heuristicus** [comment]
Yes, it would be great if you could try using it for a bit just to check that the bits you use regularly still work as expected. Compilation and startup works fine but there may be some parts where I've missed removing some references because pycharm can't detect all usages of something.

**Comment by heuristicus** [comment]
The failing test is testValevFitStereo, which fails because a) I removed the valkyrie component of the feet midpoint computation (I assume it's no longer needed...) and b) because it relies on lcmdrc which no longer exists.

**Comment by mauricefallon** [comment]
seemed to working when I tested now on the simulator. great job!

**Pull request merged**
