### PR TITLE
unsubscribe to topic

### PR DESCRIPTION
**Pull request by benoit-robotics**
@heuristicus 
Unsubscribe to topic when "sources" are not visible.
It doesn't work when I do exactly the same thing for DepthImagePointCloudSource, in this case director hangs or crashes
https://github.com/ori-drs/director/blob/a1c5c2bf813d463de5e9216ce5c976c6c6ff09bb/src/python/director/perception.py#L1044 .

Any idea why ?

### CODE REVIEW

**Comment by heuristicus** [comment]
I have no idea. What's the crash.

**Comment by benoit-robotics** [comment]
something about boost mutex

**Comment by benoit-robotics** [comment]
I am going to merge that, but the crash seems to be related to the "provider"

**Comment by heuristicus** [comment]
Please make an issue for it.

**Pull request merged**
