### PR TITLE
Separate ROS from director

### PR DESCRIPTION
**Pull request by heuristicus**
This completes most of the changes required by https://github.com/ori-drs/drs_base/issues/169 but requires testing with the real and simulated systems for more confidence that everything works as expected.

This doesn't fix the issue of director nodes not being shutdown when director shuts down.

Also currently ignores most of the `_onPropertyChanged` functions in terms of starting and stopping the subscribers with new topic names. @benoit-robotics Is this functionality used?

This is related to https://github.com/ori-drs/drs_base/pull/186, https://github.com/ori-drs/director_drs/pull/115.

### CODE REVIEW

**Comment by heuristicus** [comment]
Added some stuff to handle changes to properties on perception objects, and have tested with a bagfile. Can see the elevation map and cameras, and joint motion is working as expected.

**Comment by heuristicus** [comment]
This has now been tested in simulation and on the opc controlling the actual robot with no issues, so I think it's ready to merge.

@mauricefallon any sort of protocol with these sorts of non-trivial changes?

**Comment by mauricefallon** [comment]
hi @heuristicus , apologies with not engaging on this. I have been busy with lectures and exam setting. my last lecture is today. i'll swing around to this with high priority after that.

given its a major revamp, I'd like to check it myself - but I note that you have done a lot of testing yourself.

**Comment by heuristicus** [comment]
I realised yesterday that there's still a bit that I haven't checked which is @benoit-robotics addition of markers and marker arrays for something to do with aicp as far as I remember.

**Pull request merged**
